version: "3.9"

services:
  frontend:
    image: airknightash/todo-frontend:1.0.0
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://backend:4000
    depends_on:
      - backend

  backend:
    image: airknightash/todo-backend:1.0.0
    container_name: todo-backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: ${TODO_DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: ${TODO_DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
